CREATE SCHEMA IF NOT EXISTS "pgmq_public";

CREATE EXTENSION IF NOT EXISTS "pgmq" WITH SCHEMA "pgmq_public";

SELECT FROM pgmq.create('emails');

alter table pgmq.q_my_queue enable row level security;

create policy "Allow anon and authenticated to access messages from queue" 
on "pgmq"."emails" 
as PERMISSIVE 
for ALL 
to anon, authenticated 
using (true) 
with check (true);



create table if not exists email_template (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "from" text not null,
  subject text not null,
  text text null,
  attachments jsonb null,
  html text not null,
  constraint email_template_pkey primary key (id)
);


create table if not exists processed_emails (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  smtp_successful boolean not null,
  email_id bigint not null,
  smtp_error_msg text null,
  email_to text not null,
  queue_msg_id bigint not null,
  constraint processed_emails_pkey primary key (id),
  constraint processed_emails_email_id_fkey foreign KEY (email_id) references email_template (id)
);